# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
	config.vm.box = "xenial/ubuntu-16.04"

    config.vm.define :server do |server_config|
        server_config.vm.hostname = 'data61_server'
        server_config.vm.network "private_network", ip: "192.168.33.10"
    end
 
    config.vm.provider :virtualbox do |virtualbox_config|
        virtualbox_config.name = "myvm"
		virtualbox_config.gui = false
	    virtualbox_config.memory = "4096"
    end
 
    config.vm.provision :shell, path: "prereq.sh"
 
end